In [4]:
import pandas as yshu

print(pandas.__version__)

NameError: name 'pandas' is not defined

In [ ]:
smartgrowemployees = ["Keerthi", "Madhav", "Baji", "balaji", "vaishu","vinay"]

temp = yshu.Series(smartgrowemployees,index = [1,2,3,4,5,6])
temp

1    Keerthi
2     Madhav
3       Baji
4     balaji
5     vaishu
6      vinay
dtype: object

In [ ]:
arr = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
temp_01 = yshu.DataFrame(arr)

In [ ]:
print(temp)
temp_01

1    Keerthi
2     Madhav
3       Baji
4     balaji
5     vaishu
6      vinay
dtype: object

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:


student = {
    "name": [
        "Madhav", "Vaishu", "Rahul", "Priya", "Amit",
        "Sneha", "Rohan", "Anjali", "Kiran", "Neha"
    ],
    "age": [
        21, 21, 22, 20, 23,
        22, 21, 20, 24, 22
    ],
    "Grade": [
        500, 100, 450, 380, 420,
        390, 470, 410, 460, 440
    ]
}

temp_dict = yshu.DataFrame(student)

In [ ]:
temp_dict

     name  age  Grade
0  Madhav   21    500
1  Vaishu   21    100
2   Rahul   22    450
3   Priya   20    380
4    Amit   23    420
5   Sneha   22    390
6   Rohan   21    470
7  Anjali   20    410
8   Kiran   24    460
9    Neha   22    440

In [5]:
import pandas as yshu
india = yshu.read_csv("customers-100.csv")
india

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [ ]:
india.tail()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [13]:
india.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [ ]:
india.describe()

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [16]:
india.abs

<bound method NDFrame.abs of     Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter
1       2  1Ef7b82A4CAAD10    Preston    Lozano
2       3  6F94879bDAfE5a6        Roy     Berry
3       4  5Cef8BFA16c5e3c      Linda     Olsen
4       5  053d585Ab6b3159     Joanna    Bender
..    ...              ...        ...       ...
95     96  cb8E23e48d22Eae       Karl     Greer
96     97  CeD220bdAaCfaDf       Lynn  Atkinson
97     98  28CDbC0dFe4b1Db       Fred    Guerra
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer
99    100  2354a0E336A91A1   Clarence    Haynes

                            Company               City  \
0                   Rasmussen Group       East Leonard
1                       Vega-Gentry  East Jimmychester
2                     Murillo-Perry      Isabelborough
3   Dominguez, Mcmillan and Donovan         Bensonview
4          Martin, Lang and Andrade     West Priscilla
..                              ...                ...
95                        Carey LLC       East Richard
96            Ware, Burns and Oneal       New Bradview
97                    Schmitt-Jones         Ortegaland
98               Fitzgerald-Harrell    Lake Elijahview
99               Le, Nash and Cross          Judymouth

                       Country                 Phone 1  \
0                        Chile            229.077.5154
1                     Djibouti              5153435776
2          Antigua and Barbuda         +1-539-402-0259
3           Dominican Republic  001-808-617-6467x12895
4   Slovakia (Slovak Republic)  001-234-203-0635x76146
..                         ...                     ...
95                      Guyana     (188)169-1674x58692
96                   Sri Lanka         +1-846-706-2218
97             Solomon Islands    +1-753-067-8419x7170
98                       Aruba           (530)311-9786
99                    Honduras           (753)813-6941

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24
1         686-620-1820x944                 vmata@colon.com        2021-04-23
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17
..                     ...                             ...               ...
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
0          http://www.stephenson.com/
1               http://www.hobbs.com/
2            http://www.lawrence.com/
3          http://www.good-lyons.com/
4         https://goodwin-ingram.com/
..                                ...
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

[100 rows x 12 columns]>

In [ ]:
india.isnull().sum()